apiVersion: apps/v1
kind: Deployment

metadata:
  name: client-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  
  template:
    metadata:
      labels:
        component: web
    
    spec:
      containers:
        - name: client
          image: kanand/fib_app_frontend
          ports:
            - containerPort: 3000